//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDetail
    {
        public int BankDetailsID { get; set; }
        public string BranchCode { get; set; }
        public string AccountNumber { get; set; }
        public string Bank { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
