//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload_Line
    {
        public int Upload_LineID { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public string File_Upload { get; set; }
        public string File_Type { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
